modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPL v3"
issueTrackerURL="https://github.com/North-West-Wind/ConfigComparator/issues"

[[mods]]
modId="configcomparator"
version="1.0.2"
displayName="Config Comparator"
updateJSONURL="https://github.com/North-West-Wind/ConfigComparator/raw/main/update.json"
logoFile="icon.png"
authors="NorthWestWind"
description='''
Compares the files between the client and the server. If there is a mismatch, the server will take actions.
'''

[[dependencies.configcomparator]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configcomparator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
