modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL v3"
issueTrackerURL="https://github.com/North-West-Wind/ConfigComparator/issues"

[[mods]]
modId="configcomparator"
version="2.0.0"
displayName="Config Comparator"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/ConfigComparator/main/update.json"
logoFile="icon.png"
authors="NorthWestWind"
description='''
Compares the files between the client and the server. If there is a mismatch, the server will take actions.
'''

[[dependencies.configcomparator]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configcomparator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
